export const LOAD_TESTS_SUCCESS = 'LOAD_TESTS_SUCCESS';

export const CREATE_TEST_SUCCESS = 'CREATE_TEST_SUCCESS';
export const UPDATE_TEST_SUCCESS = 'UPDATE_TEST_SUCCESS';
export const DELETE_TEST_SUCCESS = 'DELETE_TEST_SUCCESS';

export const LOGIN_APP_SUCCESS = 'LOGIN_APP_SUCCESS';
export const LOGOUT_APP_SUCCESS = 'LOGOUT_APP_SUCCESS';
export const IS_AUTHORIZE_SUCCESS = 'IS_AUTHORIZE_SUCCESS';
